name: CD

on:
  push:
    branches:
      - main

concurrency:
  group: cd-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      id-token: write

    steps:
      - name: Release
        id: release
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - name: Checkout
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup uv
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          python-version: "3.11"

      - name: Build
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        run: uv build

      - name: Publish
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        run: uv publish --trusted-publishing automatic
